In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [21]:
a=np.array(1)#0-D array
print(a)
print(a.ndim)

1
0


In [23]:
b=np.array([1,2,3,4,5])#1-D array
print(b)
print(b.ndim)

[1 2 3 4 5]
1


In [25]:
c=np.array([[1,2,3],[4,5,6]])#2-D array
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
2


In [37]:
d=np.array([[[1,2,3],[4,5,6]],[[6,2,3],[3,5,6]]])#3-D array
print(d)
print(d.ndim)


[[[1 2 3]
  [4 5 6]]

 [[6 2 3]
  [3 5 6]]]
3
